services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      DISCORD_AUTH_DISABLED: "true"
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client-dev
    ports:
      - "3000:5173"
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
